Mount the Repository under its name instead of app
espressif/esp-idf-ci-action pull request #24
Opened 2022-11-17 18:52 UTC by Fishwaldo

I'm using this to build some examples in a component I'm developing
As per the developer documentation for the components, we should use a override_path in the idf_component.yml file for each example:
https://github.com/espressif/idf-component-manager/wiki#add-examples-to-the-component

The problem is that the base path is mounted as "app" and not the component name, so when idf was trying to resolve dependencies it was failing.

This change, mounts the code under the repository name instead of app, and this idf can resolve it using the path_override. 

(maybe a better option would be to provide a config option to specify the path the repository is mounted under in the docker image?)

2022-11-21 10:28 UTC, kumekay requested changes
Hi @Fishwaldo

Thank you for the PR,
To my opinion your solution is sufficient and probably a special parameter is not needed. 
For repos with more than one component, it wouldn't be a problem because components will be in properly named subdirectories

2022-11-27 17:09 UTC, Fishwaldo commented on action.yml
> +        docker run -t -e IDF_TARGET="${IDF_TARGET}" -v "${GITHUB_WORKSPACE}:/${{ github.repository }}" -w "/${{ github.repository }}/${{ inputs.path }}" espressif/idf:${{ inputs.esp_idf_version }} ${
Good Catch. I've updated.

2022-11-30 17:18 UTC, kumekay approved these changes

2022-11-30 17:19 UTC, kumekay commented
@Fishwaldo Thank you for the improvement

2022-11-30 17:19 UTC, merged